# Generated by Django 6.0.7 on 2026-07-25 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rule_id', models.CharField(db_index=True, max_length=100)),
                ('rule_title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('src_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='new', max_length=20)),
                ('related_events', models.ManyToManyField(blank=True, related_name='alerts', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
