# Generated by Django 6.0.8 on 2026-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="group_value",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
